FORMAT: 1A

# rfdaemon API
rfdaemon API is a siimple servie to queue, run and ispect results of RobotFramework suites remotely.


## Suites Collection [/suites]
### List all Suites [GET]
+ Response 200 (application/json)

        [{
          "suite": "v210 inventory check", "tags": [ "inventory", "BIOS", "BMC", "branding" ], "documentation" : "Performs a basic inventory check of a v210 node"
        }, {
          "suite": "Ethernet bandwidth" , "tags": [ "ethernet", "benchmark"], "documentation" : "Do a simple bandwidth benchmark of the Ethernet port"
        }]

## Suite [/suites/{name}]
A single Suite object with all its details

+ Parameters
    + name (required, sting) ... String `name` of the Suite to perform action with.

### Retrieve a Suite [GET]
+ Response 200 (application/json)

        {"suite": "v210 inventory check", "tags": [ "inventory", "BIOS", "BMC", "branding" ], "documentation" : "Performs a basic inventory check of a v210 node"}

