#!/bin/bash
#
# Bring up/down rfdaemon
#
# chkconfig: - 95 10
# description: Activates/Deactivates Robot Framework test deamon
# config: /etc/rfdaemon/config
#
### BEGIN INIT INFO
# Provides:       rfdaemon
# Default-Stop:   0 1 6
# Default-Start:  3 4 5
# Required-Start: redis
# Required-Stop:  redis
# Short-Description: Starts/Stops the Robot Framework test Daemon
# Description: Starts/Stops the Robot Framework test Daemon
### END INIT INFO

. /etc/rc.d/init.d/functions

PID_FILE=/var/run/rfdaemon.pid
LOCK_FILE=/var/lock/subsys/rfdaemon
WORK_DIR=/root/test

[ -f /etc/sysconfig/rfdeamon ] && . /etc/sysconfig/rfdaemon


ACTION=$1

usage ()
{
	echo
	echo "Usage: `basename $0` {start|stop|restart|status}"
	echo
	return 2
}

start ()
{
	[ -f $LOCK_FILE ] && return 0	
	echo -n "Starting RobotFramework deamon..."
	cd $WORK_DIR
	scl enable python27 "./start.sh --pidfile $PID_FILE"
	sleep 1
	RFD_PID=`cat $PID_FILE`
	checkpid $RFD_PID
	RC=$?
	[ $RC -eq 0 ] && echo_success || echo_failure
	[ $RC -eq 0 ] && touch $LOCK_FILE
	echo
	return $RC 

}

stop ()
{
	[ -f $LOCK_FILE ] || return 0
	echo -n "Stopping RobotFramework deamon..."
	RFD_PID=`cat $PID_FILE`
	checkpid $RFD_PID
	RC=$?
	if [ $RC -ne 0 ]; then
		rm -f $PID_FILE
		rm -f $LOCK_FILE
		echo_success
		echo
		return 0
	fi
	
	kill -TERM $RFD_PID >/dev/null 2>&1
	sleep 1
	checkpid $RFD_PID
        RC=$?
        if [ $RC -ne 0 ]; then
                rm -f $PID_FILE
                rm -f $LOCK_FILE
                echo_success
		echo
                return 0
        else
		echo_failure
		echo
		return 1
	fi

}
case $ACTION in
	start|stop|restart|status)
	    [ `id -u` != "0" ] && exit 4 ;;
esac

case $ACTION in
	start) start; RC=$? ;;
	stop) stop; RC=$? ;;
	restart) restart; RC=$? ;;
	status) status; RC=$? ;;
	*) usage; RC=$? ;;
esac

exit $RC

